# Teachers section

teachers:
- {avatar: 'karine.jpg',
  name: 'Karine Durães',
  email: 'karine@vilarejonutricao.com.br',
  resume: '<p><strong>Nutricionista especialista em nutrição em pediatria</strong>
          pelo Instituto da Criança da Faculdade de Medicina na USP, pós graduada
          em fitoterapia e alimentos funcionais, iniciou sua carreira há 11 anos
          em banco de leite referência de São Paulo.</p>'}
- {avatar: 'thais.jpg',
  name: 'Thais Pontes Moreira',
  email: 'thais.moreira@correcutia.com',
  resume: '<p><strong>Graduada em Comunicação das Artes do Corpo com habilitação
          em dança</strong> pela PUC/SP, atualmente cursa Pedagogia no Instituto
          Singularidades. Desde 2009 estuda e pesquisa as artes circenses
          especializando-se em acrobacia aérea.</p>'}
- {avatar: 'romulo.jpg',
  name: 'Romulo Venoso',
  email: 'romulo.venoso@correcutia.com',
  resume: '<p><strong>Romulo Venoso, professor formado em Educação Física</strong>,
          trabalha com crianças desde 2001. Idealizador do projeto Corre Cutia.</p>'}
- {avatar: 'rubens.jpg',
  name: 'Rubens Xavier Faria',
  email: 'rubens.faria@correcutia.com',
  resume: '<p><strong>Formado em Educação Física e Pedagogia</strong>,
          com 10 anos de experiência em educação e mais de 20 anos de
          prática em Artes Marciais.</p>'}
